sudo: required

services:
  - docker

  before_install:
    - docker build -t danilo-barbosa/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true danilo-barbosa/docker-react npm run test