sudo: required
services:
  - docker
before_install:
  - 'docker build -t dbs -f Dockerfile.dev .'
script:
  - 'docker run -e CI=true dbs npm run test'
branches:
  only:
    - master
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-936539926685"
  bucket_path: "docker-react"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"